### ISSUE TITLE
request help on the underlined technology

### ISSUE THREAD

**Issue by ttbuffey** [affinda/affinda-python#1]
Dear expert,

I am quite interested in how you can remove the person photos in a resume, it seems awesome.
Is it based on AI models or just simple libraries can achieve that, I can't find any information about this.

Sincerely hope you can give me some clue. Thanks very much.

Best Regards,
ttbuffey

**Comment by andrewbird2** [comment]
Hi @ttbuffey  -  there are many ways to do this!  
For example, checkout https://github.com/facebookresearch/detectron2.  You could train a detectron2 model to recognise peoples faces, then use the output to draw a box over the person's face.

**Comment by ttbuffey** [comment]
@andrewbird2 Great thanks to you, it helps me a lot.
