### ISSUE TITLE
[ENHANCEMENT]  Is there any way to add / search resumes by tags from Python API?

### ISSUE THREAD

**Issue by oggreo** [affinda/affinda-python#2]
The web based interface allows adding of tags. I am wondering if there is any to add / search resumes using the API?

**Comment by andrewbird2** [comment]
Hi! I gather from your other issue that you've discovered the resume search and match feature, will close this for now.

**Comment by oggreo** [comment]
> Hi! I gather from your other issue that you've discovered the resume search and match feature, will close this for now.

Hello! Thanks for the quick reply. The resume search and match feature does not seem to allow search by Tags. Am I missing something?

**Comment by andrewbird2** [comment]
No we don't currently have that supported.  We may be able to add it though or discuss using custom fields for your use case.  Feel free to get in touch with sales@affinda.com to discuss with the team.
Cheers,
Andrew
