### ISSUE TITLE
[BUG] How can I use customData for search?

### ISSUE THREAD

**Issue by oggreo** [affinda/affinda-python#3]
ResumeSearchParameters() provides custom_data field to add custom data via ResumeSearchParametersCustomData Objects but it's not documented how I can do this.

I would like to search for resume based on Referees. Could you provide a guidance or example?

Thanks!

**Comment by andrewbird2** [comment]
Unfortunately this feature is something we have to enable for your organisation and is only generally setup for paid accounts.  Please get in touch with sales@affinda.com if you use case where this might be required.
