### ISSUE TITLE
[BUG] Index a new document throws an error

### ISSUE THREAD

**Issue by oggreo** [affinda/affinda-python#4]
**Describe the bug**
Index a new document API using create_index_document() returns an error. I ran the exact code from the example and made sure that identifier and index_name both exists.

`from affinda import AffindaAPI, TokenCredential

token = "REPLACE_TOKEN"
index_name = "REPLACE_INDEX_NAME"
identifier = "REPLACE_IDENTIFIER"

credential = TokenCredential(token=token)
client = AffindaAPI(credential=credential)

request_body = {
    "document": identifier,
}

resp = client.create_index_document(name=index_name, body=request_body)

print(resp.as_dict())`

This is the error that is returned

{'type': 'validation_error', 'errors': [{'attr': 'non_field_errors', 'code': 'unique', 'detail': 'The fields document, index must make a unique set.'}]}

This used to work last month... Can you help me with this? Thanks!

**Environment**
 - Client version: '1.5.0'

**Comment by alecbarber** [comment]
Hi @oggreo, each document can only be added to an index once. This error means that the document you're adding is already in the index. We've put an improvement in the pipeline to upgrade this error message to something clearer.
