### ISSUE TITLE
[BUG] subclass is not being applied to get_document()

### ISSUE THREAD

**Issue by pat-fama** [affinda/affinda-python#5]
**Describe the bug**
using `create_document()` with `wait=true` will return the proper subclass like `ResumeData` for the data property and the doc response itself has `"extractor": "resume",`.   Using `get_document()`. returns`Document`, has `"extractor": null,` and i see `Discriminator extractor is absent or null, use base class Document` in the logs
**To Reproduce**
1.  Call get_document() on a Resume
2. return object named document   document.data is a dict and not an object
4. See notice in log  `Discriminator extractor is absent or null, use base class Document`

**Expected behavior**
grabbing a document should resolve to its Subclass

**Environment**
affinda==4.7.1
Python 3.9.16

**Additional context**
raw logs still has extractor as resume, but when deserialized its null. 
This worked before.

**Comment by alecbarber** [comment]
Hi @pat-fama, thanks for raising this! The issue should be fully resolved in [v4.8.1](https://github.com/affinda/affinda-python/releases/tag/v4.8.1)
